### PR TITLE
Adapt example paths for 0.10 release

### PR DESCRIPTION
**Pull request by tillrohrmann**

### CODE REVIEW

**Comment by aljoscha** [comment]
Thanks for your contribution. :smile:

**Comment by tillrohrmann** [comment]
Always happy to contribute back to a great project :-)

**Comment by rmetzger** [comment]
I'm excited to see this project growing. Keep it up guys

**Comment by tillrohrmann** [comment]
Extrapolating our current growth, we can soon be expected to become a top level project. I did some serious research on it https://xkcd.com/605/.

**Comment by rmetzger** [comment]
This looks like science, so it must be true.

**Pull request merged**
